# Generated by Django 5.1.3 on 2024-11-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_book_hashtags_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
